---
version: 1.3.2
slug: assist_microphone_ng
name: Assist Microphone NG
description: Use Assist with local microphone
url: https://github.com/m0rdras/hass-addons/blob/master/assist_microphone_ng
hassio_api: true
arch:
  - amd64
  - aarch64
init: false
discovery:
  - wyoming
map:
  - share:ro
options:
  awake_wav: "/usr/src/sounds/awake.wav"
  done_wav: "/usr/src/sounds/done.wav"
  sound_enabled: true
  noise_suppression: 0
  auto_gain: 0
  mic_volume_multiplier: 1.0
  sound_volume_multiplier: 1.0
  snd_command_rate: 22050
  mic_seconds_to_mute_after_awake_wav: 0.5
  mic_no_mute_during_awake_wav: false
  debug_logging: false
schema:
  awake_wav: str
  done_wav: str
  sound_enabled: bool
  noise_suppression: int
  auto_gain: int
  mic_volume_multiplier: float
  sound_volume_multiplier: float
  snd_command_rate: int
  mic_seconds_to_mute_after_awake_wav: float
  mic_no_mute_during_awake_wav: bool
  debug_logging: bool
audio: true
homeassistant: 2023.12.1
image: ghcr.io/m0rdras/{arch}-addon-assist_microphone_ng
